name: wise_clock
description: "A Flutter application for managing work hours and records."
publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  uuid: ^4.5.1
  flutter_gen: ^5.10.0

  go_router: ^15.1.2
  intl: ^0.20.2
  wheel_picker: ^0.2.1
  # table_calendar: ^3.2.0
  table_calendar:
    git:
      url: https://github.com/rt234cw/table_calendar.git # PR 來源的儲存庫 URL
      ref: feat/only-week-days                           # PR 來源的分支名稱
  rxdart: ^0.28.0
  collection: ^1.19.1
  hive_generator: ^2.0.1
  dropdown_button2: ^2.3.9
  provider: ^6.1.5
  flutter_native_splash: ^2.4.6
  data_table_2: ^2.6.0
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
flutter_intl:
  enabled: true
  main_locale: en


flutter_native_splash:
  color: "#1A1A1A"
  image: assets/images/app_icon.png